# Generated by Django 3.1.2 on 2020-10-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201010_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
